"use client";

import Sidebar from "@/components/sidebar/Sidebar";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Provider } from "react-redux";
import store from "@/store/store";
import { QueryClient, QueryClientProvider } from "react-query";
import { useEffect, useLayoutEffect, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { CookiesProvider } from "react-cookie";

// export const metadata = {
//   title: "Matterbay",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [loading, setLoading] = useState(true);

  const router = useRouter();
  const pathname = usePathname();

  useLayoutEffect(() => {
    if (pathname === "/auth/register") router.push("/auth/register");

    if (pathname === "/auth/login") router.push("/auth/login");
    setLoading(false);
  }, [pathname, router]);

  const queryClient = new QueryClient();


  


  return (
    <html lang="en">
      <body className="flex flex-col lg:flex-row h-screen  ">
        <CookiesProvider defaultSetOptions={{ path: '/' }}>
          <Provider store={store}>
            <QueryClientProvider client={queryClient}>
      

           
              {/* <Sidebar /> */}

              {/* <div className="flex flex-col">
              <Navbar />
            </div> */}

              <main className="flex-1 bg-[#f6f7fb] lg:w-4/5">{children} </main>
         
            </QueryClientProvider>
          </Provider>
        </CookiesProvider>
      </body>
    </html>
  );
}


